### ISSUE TITLE
The parameter "clientToken" is NOT required in authlib-injector documentation

### ISSUE THREAD

**Issue by allMagicNB** [elyby/accounts#35]
The parameter "clientToken" is NOT required in authlib-injector documentation, but it is required in Ely.by.

**Comment by erickskrauch** [comment]
Could you please explain the problem with some links and more details?

**Comment by allMagicNB** [comment]
https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E7%99%BB%E5%BD%95

**Comment by erickskrauch** [comment]
I believe we've made the implementation in such a way because the Mojang were doing so. Without the `clientToken` you won't be able to refresh the token later. Right now there is no way to check the official implementation since it's disabled. But I see that this behavior is declared for authlib-injector's routes, so I this we must implement it too.

**Comment by allMagicNB** [comment]
Look at this: Hex-Dragon/PCL2#5135

**Comment by allMagicNB** [comment]
🤔https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E5%88%B7%E6%96%B0

**Comment by allMagicNB** [comment]
wiki.vg: https://wiki.vg/Legacy_Mojang_Authentication#Authenticate

**Comment by erickskrauch** [comment]
@allMagicNB, the requested changes have been implemented and deployed. Thank you for the report!
