### ISSUE TITLE
[Feature] plan to make an OAuth device flow code sign-in for the initiator？

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [elyby/accounts#37]
# The Yggdrasil documentation doesn't require this feature, so this is an optional feature.

Littleskin already implements OAuth logins based on device code flows, so please ask if ely.by has a similar plan, as existing OAuth logins only have authorization code flow logins, which doesn't work with third-party Minecraft launchers.

### Note: Device flow code sign-in has certain security risks

**Comment by Octol1ttle** [comment]
Device code sign-in is implemented on the backend, but there's still work to do on the frontend before the feature can be fully used. We'll get back to you once it's ready.

**Comment by wuliaodexiaoluo** [comment]
> Device code sign-in is implemented on the backend, but there's still work to do on the frontend before the feature can be used. We'll get back to you once it's ready.

Wow, that's amazing

**Comment by erickskrauch** [comment]
Resolved. While the documentation needs to be written, use the tests as the documentation.
https://github.com/elyby/accounts/blob/1c11c66b9cbcf1d804c9277756266cf9c507b7d5/api/tests/functional/oauth/DeviceCodeCest.php#L57-L95

**Comment by shimoranla** [comment]
> Resolved. While the documentation needs to be written, use the tests as the documentation. 

The login process will be rewritten over the weekend to be compatible with ely.by's OAuth login system.

Thanks!

**Comment by tnqzh123** [comment]
@erickskrauch @Octol1ttle 

We at @LittleSkinChina are planning to create a new protocol for Yggdrasil auth server named Yggdrasil Connect that based on OpenID Connect and its extension MS-OIDCE, utilizing the ID Token and `UserInfo` endpoint to deliver user info and player profile, while using the OAuth Access Token itself to join the Minecraft game server. How do you feel this sounds like? Would you like to implement it?

P.S. The session server part is unchanged, as it follows authlib-injector's Yggdrasil API specification.

**Comment by erickskrauch** [comment]
![No, I don't think I will](https://github.com/user-attachments/assets/04941d15-3786-46c7-9a45-4c8b5c0b9ae4)

We are already have an auth code and device code grants. Please, use the exists and standardized protocols. This will help the whole community more than a yet another protocol.

**Comment by tnqzh123** [comment]
@erickskrauch 

> We are already have an auth code and device code grants. Please, use the exists and standardized protocols. This will help the whole community more than a yet another protocol.

I got your mean, and I totally agree with it.

But the thing is, the current OAuth 2.0 authorization flow is not standardized that much. Every OAuth 2.0 Authorization Server may have its own URL of Authorization Endpoint and Token Endpoint, while the scopes and user info data structure may be different by AS too. The client has no way to get known about it until developers write specified codes with specified AS. Although RFC 8414 (OAuth 2.0 Authorization Server Metadata) has defined the way OAuth 2.0 authorization endpoints could be discovered, it seems that literally nobody has implemented it, neither Ely.by.

We think this situation is not good for the community. That's why we at @LittleSkinChina want a new standardized protocol, just like #2 did.

OpenID Connect is an authentication layer on top of OAuth 2.0 protocol (RFC 6749 and others), allowing clients to authenticate users and obtain identity information in a standardized way. You can treat it as "enhanced OAuth 2.0". It means you can keep the current OAuth 2.0 authorization grant flow (authorization code, implicit, and maybe more) and just implement OIDC on the top of it - That's the reason we chose to build the new Yggdrasil Connect protocol based on OIDC.

By defining standardized scopes, ID Token and `UserInfo` endpoint in OIDC Core specification, OIDC make it possible for applications to get user info across different OpenID Providers easily. OIDC also defined how the service and endpoints could be discovered in OIDC Discovery specification, also on the top of RFC 8414. Generally speaking, OIDC eliminates most of obstacles in authorization and user authentication for third-party applications in OAuth 2.0.

Based on the above, Yggdrasil Connect is really simple. What YggC will do is basically defining some scopes and adding some claims in OIDC ID Token and `UserInfo` endpoint. By implementing YggC, all launchers could authenticate with different Yggdrasil servers by OAuth 2.0 and OIDC, getting much more security than traditional username and password login.

How does it feel like now?
